name: Build and Deploy with Docker

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      # 1. GitHub 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build project with Gradle
        run: ./gradlew clean build

      # 3. Docker 이미지 빌드
      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64 -t sohyun022/sca .

      
      # 4. Docker 이미지 푸시
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sca:latest

      # 5. EC2 서버에 이미지 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/sca:latest
            docker stop seoul-congestion || true
            docker rm seoul-congestion || true
            docker run -d --name seoul-congestion -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/sca:latest
